### ISSUE TITLE
Follow-Up to issue #1 (project- / framework-wide config)

### ISSUE THREAD

**Issue by pfweberp** [JSzaszvari/rundeck-rocketchat-notifier#2]
Hey,

as already mentioned in https://github.com/jszaszvari/rundeck-rocketchat-notifier/issues/1
we're looking really forward to the update on this plugin.

Can you already estimate when the next release with a possible project-wide configuration is available?
We're very interested in this feature as we don't want to configure 25 jobs in each of our 8 projects.

**Comment by JSzaszvari** [comment]
PR was merged with new features
